apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/abhijith3707/spring-framework-petclinic.git'
    targetRevision: HEAD
    path: 'manifest' # Adjust this path as per your repo structure
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: petclinic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
