apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: 863518452866.dkr.ecr.us-west-2.amazonaws.com/petclinic:latest  # Your ECR image
          ports:
            - containerPort: 8080
